# Generated by Django 4.2 on 2023-05-04 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_reserva_delete_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='habitacion',
            new_name='area',
        ),
    ]
