# Generated by Django 4.2 on 2023-05-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_reservaareascomunes_delete_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservamicondominio',
            fields=[
                ('NumeroEdificio', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreResidente', models.CharField(max_length=50)),
                ('Area', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ReservaAreasComunes',
        ),
    ]
