# Generated by Django 4.2 on 2023-05-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_reservamicondominio_area'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservamicondominio',
            table='reservamicondominio',
        ),
    ]
