# Generated by Django 4.2 on 2023-05-07 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_reservamicondominio_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservamicondominio',
            table=None,
        ),
    ]
