# Generated by Django 4.2 on 2023-05-09 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_reservamicondominio_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservamicondominio',
            name='FechaEstimada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
