# Generated by Django 4.2 on 2023-05-12 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_reservamicondominio_fechaestimada'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservarechazada',
            fields=[
                ('NumeroEdificio', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreResidente', models.CharField(max_length=50)),
                ('Area', models.CharField(max_length=10)),
                ('FechaEstimada', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
